{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forge.fullname" . }}-secrets
  labels:
    {{- include "forge.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  database-url-replica: {{ .Values.secrets.databaseUrlReplica | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
{{- end }}
